# Generated by Django 2.2.4 on 2019-09-07 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='category',
            field=models.CharField(choices=[('news', 'News archives'), ('leak', 'Leaks'), ('land', 'Land registry'), ('gazette', 'Gazettes'), ('court', 'Court archives'), ('company', 'Company registries'), ('sanctions', 'Sanctions lists'), ('procurement', 'Procurement'), ('finance', 'Financial records'), ('grey', 'Grey literature'), ('library', 'Document libraries'), ('license', 'Licenses and concessions'), ('regulatory', 'Regulatory filings'), ('poi', 'Persons of interest'), ('customs', 'Customs declarations'), ('census', 'Population census'), ('transport', 'Air and maritime registers'), ('other', 'Other material')], default='other', max_length=15, verbose_name='Тип датасету в класифікації OCCRP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Опис набору даних'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='slug',
            field=models.CharField(choices=[('admin', 'Administration'), ('auth', 'Authentication and Authorization'), ('contenttypes', 'Content Types'), ('sessions', 'Sessions'), ('messages', 'Messages'), ('sitemaps', 'Site Maps'), ('sites', 'Sites'), ('staticfiles', 'Static Files'), ('postgres', 'PostgreSQL extensions'), ('pipeline', 'Pipeline'), ('ckeditor', 'Ckeditor'), ('ckeditor_uploader', 'Ckeditor_Uploader'), ('abstract', 'Abstract'), ('smida', 'Власники значної частки СМІДА'), ('posipaky_info', 'Помічники народних депутатів'), ('posipaky_2_info', 'Помічники місцевих депутатів'), ('edrdr', 'Єдиний державний реєстр юросіб (ЄДР)'), ('garnahata_in_ua', 'Реєстр власників елітної нерухомості'), ('vkks', "Декларації родинних зв'язків суддів та кандидатів"), ('nacp_declarations', 'Електронні декларації'), ('paper_declarations', 'Паперові декларації'), ('cvk_2015', 'Учасники місцевих виборів 2015-го року'), ('smida_reports', 'Звіти акціонерних товариств СМІДА'), ('dabi_licenses', 'Ліцензії ДАБІ'), ('dabi_registry', 'Реєстр дозволів ДАБІ'), ('geoinf_licenses', 'Ліцензії ДП Геоінформ'), ('mbu', 'Містобудівні умови м. Києва'), ('company_house_ua', 'Британський реєстр компаній'), ('tax_debts', 'Податковий борг'), ('procurement_winners', 'Переможці в закупівлях'), ('lets_party', 'Фінансові звіти партій та кандидатів'), ('corrupt', 'Особи, засуджені за корупцію'), ('search', 'Search'), ('raven_contrib_django', 'Raven'), ('debug_toolbar', 'Debug Toolbar')], max_length=50, primary_key=True, serialize=False, verbose_name='Ідентифікатор датасету'),
        ),
    ]
