# Generated by Django 2.2.4 on 2019-09-07 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract', '0003_auto_20190907_1846'),
    ]

    database_operations = [migrations.AlterModelTable('DataSource', 'search')]

    state_operations = [migrations.DeleteModel('DataSource')]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]