# Generated by Django 3.1.1 on 2020-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_andoz_tj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryandoztjmodel',
            name='data',
            field=models.JSONField(null=True, verbose_name='Дані'),
        ),
    ]
