# Generated by Django 2.2.4 on 2019-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_winners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementwinnersmodel',
            name='winner_code',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Procurement winner code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementwinnersmodel',
            name='winner_name',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
    ]
