# Generated by Django 2.2.4 on 2019-08-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letspartymodel',
            name='type',
            field=models.CharField(choices=[('nacp', 'Звіти партій (НАЗК)'), ('parliament', 'Звіти парламентських виборів (ЦВК)'), ('president', 'Звіти президентських виборів (ЦВК)')], default='nacp', max_length=10, verbose_name='Джерело даних'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letspartymodel',
            name='ultimate_recepient',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Кінцевий отримувач коштів'),
            preserve_default=False,
        ),
    ]
