# Generated by Django 2.2.4 on 2019-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0003_auto_20190814_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letspartymodel',
            name='type',
            field=models.CharField(choices=[('nacp', 'Звіти партій до НАЗК'), ('parliament', 'Попередні звіти парламентських виборів до ЦВК'), ('president', 'Попередні звіти президентських виборів до ЦВК'), ('parliament_final', 'Звіти парламентських виборів до ЦВК'), ('president_final', 'Звіти президентських виборів до ЦВК')], max_length=20, verbose_name='Джерело даних'),
        ),
    ]
