# Generated by Django 2.2.4 on 2019-09-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0004_auto_20190819_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letspartymodel',
            name='type',
            field=models.CharField(choices=[('nacp', 'Звіти партій до НАЗК'), ('parliament', 'Звіти парламентських виборів до ЦВК'), ('president', 'Звіти президентських виборів до ЦВК')], max_length=20, verbose_name='Джерело даних'),
        ),
    ]
