# Generated by Django 2.2.4 on 2019-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0006_letspartyredflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='letspartyredflag',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
