# Generated by Django 2.2.4 on 2019-09-15 10:26

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0007_letspartyredflag_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letspartyredflag',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Додаткові відомості'),
        ),
    ]
