# Generated by Django 2.2.4 on 2019-09-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0008_auto_20190915_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letspartyredflag',
            name='rule',
            field=models.CharField(choices=[('company_won_procurement', 'Компанія виграла у держзакупівлях'), ('company_had_tax_debts', 'Компанія мала держборг'), ('company_is_high_risk', 'Компанія має ознаки фіктивності'), ('company_has_foreign_bo', 'Компанія має закордоних бенефіціарів'), ('company_has_pep_bo', 'Компанія має PEP-бенефіціарів')], max_length=100),
        ),
    ]
