# Generated by Django 2.2.4 on 2019-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0009_auto_20190916_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='letspartymodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сума пожертви'),
        ),
        migrations.AlterField(
            model_name='letspartyredflag',
            name='rule',
            field=models.CharField(choices=[('company_won_procurement', 'Компанія виграла у держзакупівлях'), ('company_had_tax_debts', 'Компанія мала держборг'), ('company_is_high_risk', 'Компанія має ознаки фіктивності'), ('company_has_foreign_bo', 'Компанія має закордоних бенефіціарів'), ('company_has_pep_bo', 'Компанія має PEP-бенефіціарів'), ('company_is_not_active', 'Компанія припинена, або порушено справу про банкрутство'), ('company_has_pep_founder', 'Компанія має засновників/співвласників PEP-ів'), ('company_had_pep_founder', 'Компанія мала засновників/співвласників PEP-ів'), ('company_had_pep_bo', 'Компанія мала PEP-бенефіціарів')], max_length=100),
        ),
    ]
