# Generated by Django 2.2.4 on 2019-09-22 16:36

import re
from tqdm import tqdm
from django.db import migrations, models
import django.db.models.deletion

def parse_years(apps, schema_editor):
    LetsPartyModel = apps.get_model("lets_party", "LetsPartyModel")
    qs = LetsPartyModel.objects.all()

    for rec in tqdm(qs.iterator(), total=qs.count()):
        m = re.search(r"(\d{4})", rec.period)
        if m:
            rec.year = int(m.group(1))
            rec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0010_auto_20190916_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='letspartymodel',
            name='year',
            field=models.IntegerField(default=2019, verbose_name='Рік'),
        ),
        migrations.AlterField(
            model_name='letspartyredflag',
            name='rule',
            field=models.CharField(choices=[('company_won_procurement', 'Компанія виграла у держзакупівлях'), ('company_had_tax_debts', 'Компанія мала податковий борг'), ('company_is_high_risk', 'Компанія має ознаки фіктивності'), ('company_has_foreign_bo', 'Компанія має закордоних власників'), ('company_has_russian_bo', 'Компанія має російських власників'), ('company_has_occupied_bo', 'Компанія має власників на окупованих територіях'), ('company_has_crimea_bo', 'Компанія має власників у Криму'), ('company_has_pep_bo', 'Компанія має PEP власників'), ('company_is_not_active', 'Компанія припинена, або порушено справу про банкрутство')], max_length=100),
        ),
        migrations.AlterField(
            model_name='letspartyredflag',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='lets_party.LetsPartyModel'),
        ),
        migrations.RunPython(parse_years, reverse_code=migrations.RunPython.noop)
    ]
