# Generated by Django 2.2.4 on 2019-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0011_auto_20190922_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='letspartymodel',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='letspartyredflag',
            name='rule',
            field=models.CharField(choices=[('company_won_procurement', 'Компанія виграла у держзакупівлях'), ('company_had_tax_debts', 'Компанія мала податковий борг'), ('company_is_high_risk', 'Компанія має ознаки фіктивності'), ('company_has_foreign_bo', 'Компанія має закордоних власників'), ('company_has_russian_bo', 'Компанія має російських власників'), ('company_has_occupied_bo', 'Компанія має власників на окупованих територіях'), ('company_has_crimea_bo', 'Компанія має власників у Криму'), ('company_has_pep_bo', 'Компанія має PEP власників'), ('company_is_not_active', 'Компанія припинена, або порушено справу про банкрутство'), ('company_has_bo_changes', 'Структура власності змінилася перед пожертвою або відразу після')], max_length=100),
        ),
    ]
