# Generated by Django 2.2.4 on 2019-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_party', '0012_auto_20190925_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letspartymodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
    ]
