# Generated by Django 2.1.3 on 2019-01-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabi_registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DabiLicenseModel',
            new_name='DabiRegistryModel',
        ),
    ]
