# Generated by Django 2.1.7 on 2019-02-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamesDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=255, verbose_name='Термін')),
                ('translation', models.CharField(max_length=255, verbose_name='Переклад')),
                ('rec_type', models.IntegerField(choices=[(0, 'Слово'), (1, 'Фраза')], db_index=True, verbose_name='Тип запису')),
                ('comment', models.CharField(max_length=100, verbose_name='Опис набору даних')),
            ],
        ),
    ]
