# Generated by Django 2.2.4 on 2019-09-07 16:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190224_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('slug', models.CharField(choices=[('smida', 'Власники значної частки СМІДА'), ('posipaky_info', 'Помічники народних депутатів'), ('posipaky_2_info', 'Помічники місцевих депутатів'), ('edrdr', 'Єдиний державний реєстр юросіб (ЄДР)'), ('garnahata_in_ua', 'Реєстр власників елітної нерухомості'), ('vkks', "Декларації родинних зв'язків суддів та кандидатів"), ('nacp_declarations', 'Електронні декларації'), ('paper_declarations', 'Паперові декларації'), ('cvk_2015', 'Учасники місцевих виборів 2015-го року'), ('smida_reports', 'Звіти акціонерних товариств СМІДА'), ('dabi_licenses', 'Ліцензії ДАБІ'), ('dabi_registry', 'Реєстр дозволів ДАБІ'), ('geoinf_licenses', 'Ліцензії ДП Геоінформ'), ('mbu', 'Містобудівні умови м. Києва'), ('company_house_ua', 'Британський реєстр компаній'), ('tax_debts', 'Податковий борг'), ('procurement_winners', 'Переможці в закупівлях'), ('lets_party', 'Фінансові звіти партій та кандидатів'), ('corrupt', 'Особи, засуджені за корупцію')], max_length=50, primary_key=True, serialize=False, verbose_name='Ідентифікатор датасету')),
                ('name', models.TextField(verbose_name='Назва датасету')),
                ('url', models.URLField(blank=True, verbose_name='Джерело походження')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Опис набору даних')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Опис набору даних (in English)')),
                ('category', models.CharField(choices=[('news', 'News archives'), ('leak', 'Leaks'), ('land', 'Land registry'), ('gazette', 'Gazettes'), ('court', 'Court archives'), ('company', 'Company registries'), ('sanctions', 'Sanctions lists'), ('procurement', 'Procurement'), ('finance', 'Financial records'), ('grey', 'Grey literature'), ('library', 'Document libraries'), ('license', 'Licenses and concessions'), ('regulatory', 'Regulatory filings'), ('poi', 'Persons of interest'), ('customs', 'Customs declarations'), ('census', 'Population census'), ('transport', 'Air and maritime registers'), ('other', 'Other material')], max_length=15, verbose_name='Тип датасету в класифікації OCCRP')),
            ],
        ),
    ]
