# Generated by Django 2.2.8 on 2019-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_datasource_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='slug',
            field=models.CharField(choices=[('smida', 'Власники значної частки СМІДА'), ('posipaky_info', 'Помічники народних депутатів'), ('posipaky_2_info', 'Помічники місцевих депутатів'), ('edrdr', 'Єдиний державний реєстр юросіб (ЄДР)'), ('garnahata_in_ua', 'Реєстр власників елітної нерухомості'), ('vkks', "Декларації родинних зв'язків суддів та кандидатів"), ('nacp_declarations', 'Електронні декларації'), ('paper_declarations', 'Паперові декларації'), ('cvk_2015', 'Учасники місцевих виборів 2015-го року'), ('smida_reports', 'Звіти акціонерних товариств СМІДА'), ('dabi_licenses', 'Ліцензії ДАБІ'), ('dabi_registry', 'Реєстр дозволів ДАБІ'), ('geoinf_licenses', 'Ліцензії ДП Геоінформ'), ('mbu', 'Містобудівні умови'), ('company_house_ua', 'Британський реєстр компаній'), ('tax_debts', 'Податковий борг'), ('procurement_winners', 'Переможці в закупівлях'), ('lets_party', 'Фінансові звіти партій та кандидатів'), ('corrupt', 'Особи, засуджені за корупцію'), ('tax_reg', 'Реєстрація компаній в ДФС')], max_length=50, primary_key=True, serialize=False, verbose_name='Ідентифікатор датасету'),
        ),
    ]
