# Generated by Django 3.1.1 on 2020-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191207_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='slug',
            field=models.CharField(choices=[('registry_andoz_tj', 'Реєстр компаній')], max_length=50, primary_key=True, serialize=False, verbose_name='Ідентифікатор датасету'),
        ),
    ]
